config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :events
  resources :users_events, only: [:new, :create, :destroy]
  resources :invitations, only: [:new, :create, :destroy, :update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'events#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true
  # search by name or email
  has_many :recieved_invitations, foreign_key: :recipient_id, class_name: 'Invitation'
  has_many :created_invitations, foreign_key: :invite_creator_id, class_name: 'Invitation'
  has_many :users_events, foreign_key: :attendee_id
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_many :attended_events, through: :users_events, source: :event

  def self.search(search_string)
    unless search_string.nil? || search_string.empty?
      if search_string.chars.include?('@')
        self.where(email: search_string)
      else
        self.where('name == ? or username == ?', search_string, search_string)
      end
    else
      @users = User.all
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   sign_out_and_redirect(current_user)
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  private

  def respond_to_on_destroy
    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name), status: 303 }
    end
  end # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if user_signed_in?
      @user = User.find(current_user.id)
    else
      redirect_to root_path
    end
  end

  def index
    @users = User.search(params[:search])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-two-thirds">
        <h1 class="title is-2 has-text-white-ter">Search for users</h1>

        <%= link_to "Back to event page", event_path(params[:event_id]), class: "button is-info is-outlined" %>
        <br></br>

        <%=  form_tag users_index_path, :method => 'get' do  %>
          <%= label_tag(:search, "Search users by name or email", class: "label has-text-white-ter") %>
          <%= hidden_field_tag :event_id, params[:event_id] %>
          <div class="field is-grouped">
            <%= submit_tag("Search", :name => nil, class: "button control is-primary is-outlined") %>
            <%= text_field_tag :search, params[:search], class: "input mb-2" %>
          </div>
        <% end %>

          <hr>
        <% @users.each do |user| %>
          <p class="title is-5 has-text-white-ter"><%= user.name %></p>
          <p class="subtitle has-text-white-ter"><%= user.username %></p>
          <% if user.recieved_invitations.find_by(event_id: params[:event_id]).nil? %>
            <p><%= button_to "Send Invitation", invitations_path , params: { :invitation => { invite_creator_id: current_user.id, recipient_id: user.id, event_id: params[:event_id]}}, class: "button is-info" %></p>
          <% else %>
            <p><%= link_to "Rescind Invitation", invitation_path(user.recieved_invitations.find_by(event_id: params[:event_id])), params: {user_id: user.id, event_id: params[:event_id]}, data: {turbo_method: :delete}, class: "button is-danger is-outlined" %></p> 
          <% end %>
          <hr>
        <% end %>
        
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
  <div class="container">
    <div class="columns">
      <div class="column">

        <section class="section invitation-inbox">
          <h1 class="title is-3 has-text-white-ter"><%= @user.name %></h1>
          <%= link_to "Edit profile", edit_user_registration_path, class: "button is-white is-outlined"%>
          <br></br>
          <h2 class="title is-4 has-text-white-ter">Invitation Inbox</h2>
          <% if @user.recieved_invitations.unresponded.empty? %>
            <p class="title is-6 has-text-warning">Inbox empty</p>
          <% end %>
          <div class="columns is-multiline">
            <% @user.recieved_invitations.unresponded.each do |u| %>
              <div class="column is-one-quarter">
                <div class="box has-background-grey-dark">
                  <% if u.event.date >= Date.today %>
                    <p class="title is-5 has-text-white-ter">
                    <%= u.event.title %>
                    </p>
                    <p class="subtitle has-text-white-ter">
                    <%= u.event.date %>
                    </p>
                    <div class="field is-grouped">
                      <p class='control'>
                      <%= link_to "Details", event_path(u.event), class: "button is-primary is-outlined"%>     
                      </p>
                    </div>
                    <div class="field is-grouped">
                      <p class="control">
                      <%= link_to "Accept", invitation_path(u, :response => 'attend', :event_id => u.event.id), data:{turbo_method: :patch}, class: "button is-info" %>
                      <%= link_to "Decline", invitation_path(u, :response => 'decline'), data: {turbo_method: :patch}, class: "button is-info" %>
                      </p>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </section>

        <section class="section created-events">
          <h2 class="title is-4 has-text-white-ter">Created Events</h2>
          <h3 class="title is-5 has-text-white-ter">Private</h3>
          <div class="columns is-multiline">
            <% @user.created_events.private_event.each do |event| %>
              <%= render( "events/event_card", event: event) %>
            <% end %>
            <br>
          </div>
          <h3 class="title is-5 has-text-white-ter">Public</h3>
          <div class="columns is-multiline">
            <% @user.created_events.public_event.each do |event| %>
              <%= render("events/event_card", event: event) %>
            <% end %>
            <br>
          </div>
        </section>

        <section class="section attending-events">
          <h2 class="title is-4 has-text-white-ter">Attending Events</h2>
          <h3 class="title is-5 has-text-white-ter">Upcoming</h2>
          <div class="columns is-multiline">
            <% @user.attended_events.future.each do |event| %>
              <%= render("events/event_card", event: event) %>
            <% end %>
            <br>
          </div>
          <h3 class="title is-5 has-text-white-ter">Past</h3>
          <div class="columns is-multiline">
            <% @user.attended_events.past.each do |event| %>
              <%= render("events/event_card", event: event) %>
            <% end %>
            <br>
          </div>
        </section>

      </div>
    </div>
  </div>