config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :events
  resources :users_events, only: [:new, :create, :destroy]
  resources :invitations, only: [:new, :create, :destroy, :update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
  scope :past, -> { self.where('date < ?', Date.today).order(date: :asc) }
  scope :future, -> { self.where('date >= ?', Date.today).order(date: :asc) }
  scope :public_event, -> { self.where("visibility = 'public'").order(date: :desc) }
  scope :private_event, -> { self.where("visibility = 'private'").order(date: :desc) }

  # def self.past
  #   self.where('date < ?', Date.today)
  # end

  # def self.future
  #   self.where('date > ?', Date.today)
  # end

  has_many :invitations, dependent: :destroy
  belongs_to :creator, class_name: 'User'
  has_many :users_events
  has_many :attendees, through: :users_events

  validates :description, :title, :location, :date, :visibility, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  def index
    @events = Event.all
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      # flash.now[:notice] = 'Event was created'
      redirect_to @event, notice: 'Event successfully created'
    else
      flash.now[:alert] = 'Event fields cannot be left blank'
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated'
    else
      render :edit, status: :unprocessable_entity
      flash[:alert] = 'Event fields cannot be left blank'
    end
  end

  def destroy
    @event.destroy
    redirect_to users_show_path, status: 303
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:description, :title, :location, :date, :visibility)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_card.html.erb
<div class="column is-one-third">
   <div class="box has-background-grey-dark">
      <h2 class="has-text-white-ter title is-5"><%= event.title %></h2> 
      <p class="subtitle has-text-white-ter"><%= event.date %></p>
      <p class="has-text-white-ter"><%= event.description.truncate_words(20) %></p><br>
      <p><%= link_to "Details", event_path(event), class: "button is-primary is-outlined" %></p>
   </div> 
</div> 

app/views/events/_event_form.html.erb
<%= form_with model: @event do |f| %>
  <div class="field">
    <div class="control">
      <%= f.label :title, class: "label has-text-white-ter"%>
      <%= f.text_area :title, autofocus: true, class: "input" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :description, class: "label has-text-white-ter"%>
      <%= f.text_area :description, autofocus: true, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :location, class: "label has-text-white-ter"%>
      <%= f.text_area :location, autocomplete: "location", class: "input" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :date, class: "label has-text-white-ter"%>
      <%= f.date_field :date, class: "input" %>
    </div>
  </div>
  <br>
  <div>
    <%= f.label :visibility, "Public  ", class: "radio has-text-white-ter"%>
    <%= f.radio_button :visibility, "public" %>
    <br>
    <%= f.label :visibility, "Private  ", class: "radio has-text-white-ter" %>
    <%= f.radio_button :visibility, "private" %>
  </div>
    <br>

  <div>
    <%= f.button :submit, class: "button is-info" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-one-third">
        <h1 class="title is-2 has-text-white-ter">Edit Event</h1>

        <%= render "event_form", event: @event %>
        
      </div>
    </div>
  </div>
</section>

app/views/events/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <h1 class="title is-3 has-text-white-ter">Public Events</h1>
        <div class="columns is-multiline">
          <% @events.public_event.future.each do |event| %>
            <%= render "event_card", event: event %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
  
</section>

app/views/events/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-one-third">
        <h1 class="title is-2 has-text-white-ter">Create a New Event</h1>

        <%= render "event_form", event: @event %>
        
      </div>
    </div>
  </div>
</section>

app/views/events/show.html.erb
<%# <% unless @event.invitations %>
  <section class="section">
   <div class="container">
     <div class="columns is-centered">
       <div class="column is-half">
         <h1 class="title is-2 has-text-white-ter"><%= @event.title %></h1><br />

         <% if user_signed_in? && @event.invitations.unresponded.where(recipient_id: current_user.id).exists? && @event.date >= Date.today%>
           <h2 class="title is-4 has-text-warning">You've been invited</h2>
           <div class="field is-grouped">
             <p class="control">
             <%= button_to "Accept", invitation_path(@event.invitations.find_by(recipient_id: current_user.id)), params: {response: 'attend', event_id: @event.id }, method: :patch, class: "button is-info is-outlined" %>
             </p>
             <p class="control">
             <%= button_to "Decline", invitation_path(@event.invitations.find_by(recipient_id: current_user.id)), params: {response: 'decline'}, method: :patch, class: "button is-danger is-outlined"%>
             </p> 
           </div>
           <br>
         <% end %>

         <% if @event.date < Date.today %>
           <h2 class="title is-1 has-text-white-ter">Event sign up is closed</h2>
         <% end %>
        
         
         <h3 class="title is-4 has-text-white-ter">Description: </h3>
         <p class="subtitle has-text-white-ter"><%= @event.description %></p><br>
         <h3 class="title is-4 has-text-white-ter">Location: </h3>
         <p class="subtitle has-text-white-ter"><%= @event.location %></p><br>
         <h3 class="title is-4 has-text-white-ter">Date: </h3>
         <p class="subtitle has-text-white-ter"><%= @event.date %></p><br>
         <h3 class="title is-4 has-text-white-ter">Creator: </h3>
         <p class="subtitle has-text-white-ter"><%= @event.creator.name %><br>
         <em><%= @event.creator.username %></em></p><br>
         <h3 class="title is-4 has-text-white-ter">Creator Email: </h3>
         <p class="subtitle has-text-white-ter"><%= @event.creator.email %></p><br>

       

         <% if @event.visibility == 'public' && @event.date >= Date.today %>
           <% if !user_signed_in? %>
             <p><%= button_to "Attend Event", new_user_session_path, method: :get, class: "button is-info" %></p>
           <% else %>
             <% if UsersEvent.where(attendee_id: current_user.id, event_id: @event.id).exists? %> 
               <p><%= button_to "Not going to make it", users_event_path, method: :delete, params: {users_event_id: UsersEvent.find_by(attendee_id: current_user.id).id }, class: "button is-warning" %></p><br>
             <% else %>
               <p><%= button_to "Attend Event", users_events_path, params: { attendee_id: current_user.id, event_id: @event.id}, class: "button is-info" %></p><br>
             <% end %>
           <% end %>
         <% end %>

       </div>

       <div class="column is-one-quarter">
         <% if user_signed_in? && current_user.id == @event.creator_id %>
          <h2 class="title is-3 has-text-info">Creator dashboard</h2>
           <div class="field is-grouped">
             <p class="control"><%= link_to 'Edit Event', edit_event_path(@event), class: "button is-warning is-outlined" %></p>
             <p class="control"><%= link_to "Delete Event", event_path(@event), data: { turbo_method: :delete, confirm: "are you sure?"}, class: "button is-danger is-outlined" %></p>
           </div><br>
           <% if @event.date >= Date.today %>
             <p class="control"><%= button_to "Send Invites", users_index_path, method: 'get', params: {event_id: @event.id}, class: "button is-info" %></p>
           <% end %><br>
            <h3 class="title is-4 has-text-white-ter">Unanswered Invites</h3><hr>
             <% @event.invitations.where('response IS NULL').each do |i| %>
               <p class="title is-5 has-text-white-ter"><%= i.recipient.name %></p>
               <p class="subtitle has-text-white-ter"><%= i.recipient.username %></p>
               <br>
             <% end %>

             <br>
             <h3 class="title is-4 has-text-white-ter">Declined</h3><hr>
             <% @event.invitations.where("response = ?", 'decline').each do |i| %>
               <p class="subtitle has-text-white-ter"><%= i.recipient.name %></p>
               <br>
             <% end %>
             <br>
         <% end %>
         <h2 class="title is-3 has-text-white-ter">Attended By</h2><hr>
         <% @event.attendees.each do |a| %>
           <p class="title is-4 has-text-white-ter"><%= a.name %></p>
           <p class="subtitle is-5 has-text-white-ter"><em><%= a.username %></em></p>
         <% end %>
       </div>
     </div>
   </div> 
  </section>