config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :events
  resources :users_events, only: [:new, :create, :destroy]
  resources :invitations, only: [:new, :create, :destroy, :update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'events#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Palace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="has-background-dark is-fullheight has-navbar-fixed-top">
    <nav class="navbar has-background-black-ter is-fixed-top">
      <div class="navbar-brand">
        <figure class="image is-32x32 ml-2 mt-2">
          <%= image_tag("palace_32x32.png") %>
        </figure>
        <%= link_to root_path, class: "navbar-item" do%>
          <h1 class="title is-5 has-text-primary-light">Event Palace</h1>
        <% end %>
        <a role="button" class="navbar-burger burger", aria-label='menu', aria-expanded='false', data-target="nav-menu">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="nav-menu" class="navbar-menu has-background-black-ter">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="columns is-mobile is-centered">
              <div id='navButtons' class="column is-narrow field is-grouped">
                
                <% if user_signed_in? %>
                  <p class="control has-text-centered">
                  <%= link_to "Create Event", new_event_path, class: "button is-warning is-outlined is-fullwidth" %>
                  </p><br>
                  <p class="control has-text-centered">
                  <%= link_to current_user.name + "'s Profile", users_show_path, class: "button is-info is-outlined is-fullwidth "%>
                  </p><br>
                  <p class="control has-text-centered">
                  <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete}, class: "button is-danger is-outlined is-fullwidth"%>
                  </p><br>
                <% else %>
                  <p class="control has-text-centered">
                  <%= link_to "Sign in", new_user_session_path, class: "button is-info is-fullwidth" %>
                  </p><br>
                  <p class="control has-text-centered">
                  <%= link_to "Sign up", new_user_registration_path, class: "button is-info is-fullwidth" %>
                  </p>
              </div>
            </div>
          </div> 
        </div>
        <% end %>
      </div>
    </nav>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice has-text-grey-dark"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>